#!/bin/sh
set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ "$1" = "purge" ]; then
    rm -rf /etc/systemd/system/nitro-key-detection.service.d
    rm -f /var/run/DAMX.sock
    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload >/dev/null 2>&1 || true
    fi
fi

#DEBHELPER#

exit 0
